---
- hosts: all
  tasks:
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest
      become: yes
    - name: run apache
      command: systemctl start httpd
      become: yes
    - name: Copy vue-2048
      copy:
        src: vue-2048/dist/
        dest: /var/www/html


